server:
  port: 8081

logging:
  level:
    root: INFO
    org:
      springframework:
        web: debug
        client:
          RestTemplate: debug
        security: trace
        boot:
          autoconfigure: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:9090/auth/realms/springboot
#          issuer-uri : http://localhost:8180/auth/realms/hansel
